services:
    # Warning, do not use this directly, use the ManagerRegistry (doctrine) instead to prevent dependencies loops
    sidus_eav_model.entity_manager:
        deprecated: '%service_id% is deprecated, use the ManagerRegistry or the RepositoryFinder instead'
        class: Doctrine\ORM\EntityManagerInterface
        factory: 'Doctrine\Common\Persistence\ManagerRegistry:getManagerForClass'
        arguments:
            - '%sidus_eav_model.entity.data.class%'

    # Warning, only use this service when you need the access to the entire EAV set
    Sidus\EAVModelBundle\Entity\DataRepository:
        deprecated: '%service_id% is deprecated, use the RepositoryFinder instead'
        class: Sidus\EAVModelBundle\Entity\DataRepository
        factory: 'sidus_eav_model.entity_manager:getRepository'
        arguments:
            - '%sidus_eav_model.entity.data.class%'

    Sidus\EAVModelBundle\Doctrine\EAVFinder:
        class: Sidus\EAVModelBundle\Doctrine\EAVFinder
        arguments:
            - '@Sidus\EAVModelBundle\BaseBundle\Doctrine\RepositoryFinder'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'

    Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager:
        class: Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
