services:
    Sidus\EAVModelBundle\BaseBundle\Doctrine\RepositoryFinder:
        class: Sidus\EAVModelBundle\BaseBundle\Doctrine\RepositoryFinder
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'

    Sidus\EAVModelBundle\Doctrine\EAVFinder:
        class: Sidus\EAVModelBundle\Doctrine\EAVFinder
        arguments:
            - '@Sidus\EAVModelBundle\BaseBundle\Doctrine\RepositoryFinder'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'

    Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager:
        class: Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
