parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute

services:
    Sidus\EAVModelBundle\Doctrine\DataLoaderInterface:
        alias: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader

    Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader:
        class: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
        arguments:
            - '@Sidus\EAVModelBundle\BaseBundle\Doctrine\RepositoryFinder'

    Sidus\EAVModelBundle\Doctrine\ContextualizedDataLoaderInterface:
        alias: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
