services:
    Sidus\EAVModelBundle\Event\DoctrineMetadataListener:
        class: Sidus\EAVModelBundle\Event\DoctrineMetadataListener
        public: false
        arguments:
            - '%sidus_eav_model.entity.data.class%'
            - '%sidus_eav_model.entity.value.class%'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    Sidus\EAVModelBundle\Event\OrphanEmbedRemovalListener:
        class: Sidus\EAVModelBundle\Event\OrphanEmbedRemovalListener
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    Sidus\EAVModelBundle\Event\DoctrineToEAVEventConverter:
        class: Sidus\EAVModelBundle\Event\DoctrineToEAVEventConverter
        public: false
        arguments:
            - '@event_dispatcher'
            - '@logger'
        tags:
            - { name: doctrine.event_subscriber }
