services:
    Sidus\EAVModelBundle\Serializer\MaxDepthHandler:
        class: Sidus\EAVModelBundle\Serializer\MaxDepthHandler
        public: false

    Sidus\EAVModelBundle\Serializer\CircularReferenceHandler:
        class: Sidus\EAVModelBundle\Serializer\CircularReferenceHandler
        public: false

    Sidus\EAVModelBundle\Serializer\ByReferenceHandler:
        class: Sidus\EAVModelBundle\Serializer\ByReferenceHandler
        public: false

    Sidus\EAVModelBundle\Serializer\EntityProviderInterface:
        alias: Sidus\EAVModelBundle\Serializer\PurgeableEntityProviderInterface

    Sidus\EAVModelBundle\Serializer\PurgeableEntityProviderInterface:
        alias: Sidus\EAVModelBundle\Serializer\EntityProvider

    Sidus\EAVModelBundle\Serializer\EntityProvider:
        class: Sidus\EAVModelBundle\Serializer\EntityProvider
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
