services:
    Sidus\EAVModelBundle\BaseBundle\Translator\TranslatorDecorator:
        class: Sidus\EAVModelBundle\BaseBundle\Translator\TranslatorDecorator
        public: false
        decorates: translator
        arguments:
            - '@Sidus\EAVModelBundle\BaseBundle\Translator\TranslatorDecorator.inner'
